{{- if and .Values.rabbitmq.enabled .Values.keda.enabled (not .Values.rabbitmq.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-conn
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  url: {{ .Values.rabbitmq.url | quote }}
{{- end }}
