{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: redis:{{ .Values.redis.version }}
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
        {{- if .Values.redis.exporter.enabled }}
        - name: redis-exporter
          image: oliver006/redis_exporter:{{ .Values.redis.exporter.version }}
          ports:
            - name: metrics
              containerPort: 9121
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.redis.exporter.resources | nindent 12 }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    {{- if .Values.redis.exporter.enabled }}
    - name: metrics
      port: 9121
      targetPort: metrics
    {{- end }}
{{- end }}
