{{- if and .Values.rabbitmq.enabled .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-tracked-info-refresh-worker
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-tracked-info-refresh-worker
  minReplicaCount: {{ .Values.eveBuild.trackedInfo.refreshWorker.keda.minReplicas }}
  maxReplicaCount: {{ .Values.eveBuild.trackedInfo.refreshWorker.keda.maxReplicas }}
  pollingInterval: {{ .Values.eveBuild.trackedInfo.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.eveBuild.trackedInfo.keda.cooldownPeriod }}
  triggers:
    - type: rabbitmq
      metadata:
        queueName: tracked_info.refresh_jobs
        mode: QueueLength
        value: {{ .Values.eveBuild.trackedInfo.refreshWorker.keda.queueLength | quote }}
        protocol: amqp
      authenticationRef:
        name: {{ .Release.Name }}-rabbitmq-conn
{{- end }}
